#ifndef pbr_lighting_h
#define pbr_lighting_h

float3 compute_direct_lighting(float3 normal,
                               float3 worldPosition,
                               float3 albedo,
                               float metallic,
                               float roughness,
                               float transmission,
                               float3 viewPosition,
                               float3 lightPosition,
                               float3 ambientLightColor,
                               float ior,
                               float specularFactor,
                               float3 specularColor,
                               float3 sheenColor,
                               float sheenRoughness,
                               float clearcoatFactor,
                               float clearcoatRoughness,
                               float3 clearcoatNormal,
                               texture2d<float, access::sample> brdfLUT,
                               sampler brdfLUTSampler);

float3 compute_indirect_lighting(float3 normal,
                                 float3 worldPosition,
                                 float3 viewPosition,
                                 float3 albedo,
                                 float metallic,
                                 float roughness,
                                 float ambientOcclusion,
                                 float transmission,
                                 float clearcoatFactor,
                                 float clearcoatRoughness,
                                 float3 clearcoatNormal,
                                 texturecube<float, access::sample> prefilterEnvMap,
                                 texturecube<float, access::sample> irradianceCubeMap,
                                 texture2d<float, access::sample> brdfLUT,
                                 float ior,
                                 float specularFactor,
                                 float3 specularColor,
                                 float3 sheenColor,
                                 float sheenRoughness,
                                 texturecube<float, access::sample> prefilterSheenMap);

float3 compute_transmission_lighting(float3 Lbg,
                                     float3 normal,
                                     float3 albedo,
                                     float metallic,
                                     float transmission,
                                     float3 attenuation,
                                     float3 worldPosition,
                                     float3 viewPosition,
                                     float ior,
                                     float specularFactor,
                                     float3 specularColor);

#endif /* pbr_lighting_h */
