# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app

    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show Swift version
      run: swift --version

    - name: Setup
      run: make

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

  make-metallib:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run make
        run: make clean && make

      - name: Check for changes
        id: diff
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.diff.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "[bot] `.metallib` updates"
          body: |
            This PR was automatically generated by GitHub Actions.
            It updates the `.metallib` files in the repository.
            Do not edit this PR manually.
          commit-message: "[bot] Update `.metallib` files"
          branch: bot/make-metallib
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
